name: Build Pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  OUTPUT_FOLDER: "output"
  
jobs:
  pack-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository for deployment
        uses: actions/checkout@v7

      - name: Checkout hal-common repository
        uses: actions/checkout@v7
        with:
          repository: 0x007E/hal-common
          path: hal-common
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare library package
        run: |
          mkdir -p ./${{ env.OUTPUT_FOLDER }}/hal/common
          cp -r ./hal-common/. ./${{ env.OUTPUT_FOLDER }}/hal/common/
          
          mkdir -p ./${{ env.OUTPUT_FOLDER }}/hal/avr0/uart
          cp -r ./uart.c ./${{ env.OUTPUT_FOLDER }}/hal/avr0/uart/
          cp -r ./uart.h ./${{ env.OUTPUT_FOLDER }}/hal/avr0/uart/

      - name: Upload library package
        uses: actions/upload-artifact@v7
        with:
            name: library-package
            path: ./${{ env.OUTPUT_FOLDER }}
            retention-days: 1